#!/usr/bin/env python3
"""Handcrafted major-lang fills for all keys still missing Japanese."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LANGS = ["cn", "tw", "ja", "kr", "de", "fr", "es", "it", "pt", "br", "ru", "uk", "pl", "nl", "tr", "vn"]

# Each value is a 16-tuple matching LANGS.
# Placeholders %s/%d/%% and … must be preserved.
T: dict[str, tuple[str, ...]] = {}


def add(key: str, *vals: str) -> None:
    assert len(vals) == 16, f"{key!r} has {len(vals)} langs"
    T[key] = vals


# fmt: off
add("&Remove From History\tDel",
    "从历史记录中移除(&R)\tDel", "從歷程記錄中移除(&R)\tDel", "履歴から削除(&R)\tDel", "기록에서 제거(&R)\tDel",
    "Aus &Verlauf entfernen\tDel", "&Retirer de l’historique\tDel", "&Quitar del historial\tDel", "&Rimuovi dalla cronologia\tDel",
    "&Remover do histórico\tDel", "&Remover do histórico\tDel", "Удалить из &истории\tDel", "Видалити з &історії\tDel",
    "&Usuń z historii\tDel", "Uit &geschiedenis verwijderen\tDel", "Geçmişten &kaldır\tDel", "Xóa khỏi lịch sử(&R)\tDel")
add("&Retry",
    "重试(&R)", "重試(&R)", "再試行(&R)", "다시 시도(&R)",
    "&Wiederholen", "&Réessayer", "&Reintentar", "&Riprova",
    "&Tentar novamente", "&Tentar novamente", "&Повторить", "&Повторити",
    "&Ponów", "&Opnieuw", "&Yeniden dene", "Thử lại(&R)")
add("&Show password",
    "显示密码(&S)", "顯示密碼(&S)", "パスワードを表示(&S)", "암호 표시(&S)",
    "&Kennwort anzeigen", "&Afficher le mot de passe", "&Mostrar contraseña", "&Mostra password",
    "&Mostrar palavra-passe", "&Mostrar senha", "&Показать пароль", "&Показати пароль",
    "&Pokaż hasło", "&Wachtwoord tonen", "&Parolayı göster", "Hiện mật khẩu(&S)")
add("&Shrink To Fit",
    "缩小以适应(&S)", "縮小以符合(&S)", "ページに合わせる(&S)", "페이지에 맞춤(&S)",
    "Auf Seite &verkleinern", "A&juster à la page", "A&justar a la página", "Adatta alla &pagina",
    "A&justar à página", "A&justar à página", "Вписать в &страницу", "Вписати в &сторінку",
    "&Dopasuj do strony", "&Passend maken", "Sayfaya &sığdır", "Thu nhỏ vừa trang(&S)")
add("&Translate",
    "翻译(&T)", "翻譯(&T)", "翻訳(&T)", "번역(&T)",
    "&Übersetzen", "&Traduire", "&Traducir", "&Traduci",
    "&Traduzir", "&Traduzir", "&Перевести", "&Перекласти",
    "&Tłumacz", "&Vertalen", "&Çevir", "Dịch(&T)")
add("AI Detect TOC Pages",
    "AI 检测目录页", "AI 偵測目錄頁", "AI で目次ページを検出", "AI로 목차 페이지 감지",
    "KI-Inhaltsverzeichnisseiten erkennen", "Détecter les pages de table des matières (IA)",
    "Detectar páginas de índice (IA)", "Rileva pagine indice (IA)",
    "Detetar páginas de índice (IA)", "Detectar páginas de índice (IA)",
    "ИИ: найти страницы оглавления", "ШІ: знайти сторінки змісту",
    "Wykryj strony spisu treści (AI)", "Inhoudsopgavepagina’s detecteren (AI)",
    "İçindekiler sayfalarını algıla (AI)", "AI phát hiện trang mục lục")
add("AI Recognize Table of Contents",
    "AI 识别目录", "AI 辨識目錄", "AI で目次を認識", "AI로 목차 인식",
    "KI-Inhaltsverzeichnis erkennen", "Reconnaître la table des matières (IA)",
    "Reconocer el índice (IA)", "Riconosci l’indice (IA)",
    "Reconhecer o índice (IA)", "Reconhecer o sumário (IA)",
    "ИИ: распознать оглавление", "ШІ: розпізнати зміст",
    "Rozpoznaj spis treści (AI)", "Inhoudsopgave herkennen (AI)",
    "İçindekileri tanı (AI)", "AI nhận dạng mục lục")
add("AI returned invalid JSON.",
    "AI 返回了无效的 JSON。", "AI 傳回了無效的 JSON。", "AI が無効な JSON を返しました。", "AI가 잘못된 JSON을 반환했습니다.",
    "Die KI hat ungültiges JSON zurückgegeben.", "L’IA a renvoyé un JSON non valide.",
    "La IA devolvió un JSON no válido.", "L’IA ha restituito un JSON non valido.",
    "A IA devolveu JSON inválido.", "A IA retornou JSON inválido.",
    "ИИ вернул недопустимый JSON.", "ШІ повернув недійсний JSON.",
    "AI zwróciło nieprawidłowy JSON.", "AI gaf ongeldige JSON terug.",
    "AI geçersiz JSON döndürdü.", "AI trả về JSON không hợp lệ.")
add("AI table of contents",
    "AI 目录", "AI 目錄", "AI 目次", "AI 목차",
    "KI-Inhaltsverzeichnis", "Table des matières IA", "Índice IA", "Indice IA",
    "Índice IA", "Sumário IA", "Оглавление ИИ", "Зміст ШІ",
    "Spis treści AI", "Inhoudsopgave AI", "AI içindekiler", "Mục lục AI")
add("Add PDF TOC Item",
    "添加 PDF 目录项", "新增 PDF 目錄項目", "PDF 目次項目を追加", "PDF 목차 항목 추가",
    "PDF-Inhaltsverzeichniseintrag hinzufügen", "Ajouter une entrée de table des matières PDF",
    "Añadir entrada de índice PDF", "Aggiungi voce indice PDF",
    "Adicionar entrada de índice PDF", "Adicionar item de sumário PDF",
    "Добавить пункт оглавления PDF", "Додати пункт змісту PDF",
    "Dodaj pozycję spisu treści PDF", "PDF-inhoudsopgave-item toevoegen",
    "PDF içindekiler öğesi ekle", "Thêm mục lục PDF")
add("Add Root PDF TOC Item",
    "添加根级 PDF 目录项", "新增根層 PDF 目錄項目", "ルート PDF 目次項目を追加", "최상위 PDF 목차 항목 추가",
    "Stamm-PDF-Inhaltsverzeichniseintrag hinzufügen", "Ajouter une entrée racine de table des matières PDF",
    "Añadir entrada raíz de índice PDF", "Aggiungi voce radice indice PDF",
    "Adicionar entrada raiz de índice PDF", "Adicionar item raiz de sumário PDF",
    "Добавить корневой пункт оглавления PDF", "Додати кореневий пункт змісту PDF",
    "Dodaj główną pozycję spisu treści PDF", "Hoofditem PDF-inhoudsopgave toevoegen",
    "Kök PDF içindekiler öğesi ekle", "Thêm mục lục PDF gốc")
add("Add current page to favorites",
    "将当前页加入收藏", "將目前頁加入我的最愛", "現在のページをお気に入りに追加", "현재 페이지를 즐겨찾기에 추가",
    "Aktuelle Seite zu Favoriten hinzufügen", "Ajouter la page actuelle aux favoris",
    "Añadir la página actual a favoritos", "Aggiungi la pagina corrente ai preferiti",
    "Adicionar a página atual aos favoritos", "Adicionar a página atual aos favoritos",
    "Добавить текущую страницу в избранное", "Додати поточну сторінку до вибраного",
    "Dodaj bieżącą stronę do ulubionych", "Huidige pagina aan favorieten toevoegen",
    "Geçerli sayfayı sık kullanılanlara ekle", "Thêm trang hiện tại vào yêu thích")
add("Adjusted %d page(s) and saved to '%s'",
    "已调整 %d 页并保存到“%s”", "已調整 %d 頁並儲存到「%s」", "%d ページを調整して「%s」に保存しました", "%d페이지를 조정해 '%s'에 저장했습니다",
    "%d Seite(n) angepasst und unter „%s“ gespeichert", "%d page(s) ajustée(s) et enregistrée(s) dans « %s »",
    "%d página(s) ajustada(s) y guardada(s) en «%s»", "%d pagina/e regolata/e e salvata/e in «%s»",
    "%d página(s) ajustada(s) e guardada(s) em «%s»", "%d página(s) ajustada(s) e salva(s) em \"%s\"",
    "Скорректировано страниц: %d, сохранено в «%s»", "Скориговано сторінок: %d, збережено в «%s»",
    "Dostosowano %d stron(y) i zapisano w „%s”", "%d pagina(’s) aangepast en opgeslagen in ‘%s’",
    "%d sayfa ayarlandı ve '%s' konumuna kaydedildi", "Đã chỉnh %d trang và lưu vào '%s'")
add("An update check is already in progress.",
    "已在检查更新。", "已在檢查更新。", "更新の確認は既に進行中です。", "이미 업데이트 확인 중입니다.",
    "Eine Update-Prüfung läuft bereits.", "Une vérification de mise à jour est déjà en cours.",
    "Ya hay una comprobación de actualizaciones en curso.", "Un controllo aggiornamenti è già in corso.",
    "Já está a decorrer uma verificação de atualizações.", "Já há uma verificação de atualizações em andamento.",
    "Проверка обновлений уже выполняется.", "Перевірка оновлень уже виконується.",
    "Sprawdzanie aktualizacji jest już w toku.", "Er wordt al gecontroleerd op updates.",
    "Bir güncelleme denetimi zaten sürüyor.", "Đang kiểm tra cập nhật.")
add("Analyzing the first pages for a printed TOC…",
    "正在分析首页以查找印刷目录…", "正在分析首頁以尋找印刷目錄…", "印刷目次がないか先頭ページを分析中…", "인쇄 목차가 있는지 앞페이지 분석 중…",
    "Erste Seiten auf gedrucktes Inhaltsverzeichnis prüfen…", "Analyse des premières pages pour une table des matières imprimée…",
    "Analizando las primeras páginas en busca de un índice impreso…", "Analisi delle prime pagine per un indice stampato…",
    "A analisar as primeiras páginas para um índice impresso…", "Analisando as primeiras páginas em busca de um sumário impresso…",
    "Анализ первых страниц на печатное оглавление…", "Аналіз перших сторінок на друкований зміст…",
    "Analizowanie pierwszych stron pod kątem drukowanego spisu treści…", "Eerste pagina’s analyseren op een gedrukt inhoudsopgave…",
    "Basılı içindekiler için ilk sayfalar analiz ediliyor…", "Đang phân tích các trang đầu tìm mục lục in…")
add("Apply Crop",
    "应用裁剪", "套用裁切", "切り抜きを適用", "자르기 적용",
    "Zuschneiden anwenden", "Appliquer le recadrage", "Aplicar recorte", "Applica ritaglio",
    "Aplicar corte", "Aplicar recorte", "Применить обрезку", "Застосувати обрізання",
    "Zastosuj kadrowanie", "Bijsnijden toepassen", "Kırpmayı uygula", "Áp dụng cắt")
add("Apply Resize",
    "应用调整大小", "套用調整大小", "サイズ変更を適用", "크기 조정 적용",
    "Größe ändern anwenden", "Appliquer le redimensionnement", "Aplicar cambio de tamaño", "Applica ridimensionamento",
    "Aplicar redimensionamento", "Aplicar redimensionamento", "Применить изменение размера", "Застосувати зміну розміру",
    "Zastosuj zmianę rozmiaru", "Formaatwijziging toepassen", "Yeniden boyutlandırmayı uygula", "Áp dụng đổi kích thước")
add("Apply This Page Offset Below",
    "将此页偏移应用到下方", "將此頁位移套用到下方", "このページのオフセットを下に適用", "이 페이지 오프셋을 아래에 적용",
    "Diesen Seitenversatz darunter anwenden", "Appliquer ce décalage de page ci-dessous",
    "Aplicar este desplazamiento de página abajo", "Applica questo offset di pagina sotto",
    "Aplicar este desvio de página abaixo", "Aplicar este deslocamento de página abaixo",
    "Применить это смещение страницы ниже", "Застосувати це зміщення сторінки нижче",
    "Zastosuj to przesunięcie strony poniżej", "Deze paginaverschuiving eronder toepassen",
    "Bu sayfa ofsetini aşağıya uygula", "Áp dụng lệch trang này bên dưới")
add("Ask about the selected text…",
    "询问所选文本…", "詢問選取的文字…", "選択したテキストについて質問…", "선택한 텍스트에 대해 질문…",
    "Zum ausgewählten Text fragen…", "Poser une question sur le texte sélectionné…",
    "Preguntar sobre el texto seleccionado…", "Chiedi sul testo selezionato…",
    "Perguntar sobre o texto selecionado…", "Perguntar sobre o texto selecionado…",
    "Спросить о выделенном тексте…", "Запитати про виділений текст…",
    "Zapytaj o zaznaczony tekst…", "Vragen over de geselecteerde tekst…",
    "Seçili metin hakkında sor…", "Hỏi về văn bản đã chọn…")
add("Ask the API for model names and put the one you pick in the box. You can also type a name.",
    "向 API 请求模型名称，并将所选名称填入框中。也可以直接输入名称。",
    "向 API 要求模型名稱，並將所選名稱填入方塊。也可以直接輸入名稱。",
    "API にモデル名を問い合わせ、選んだ名前を入力欄に入れます。名前を直接入力することもできます。",
    "API에 모델 이름을 요청하고 선택한 이름을 상자에 넣으세요. 직접 입력할 수도 있습니다.",
    "Fragen Sie die API nach Modellnamen und tragen Sie den gewählten in das Feld ein. Sie können auch einen Namen tippen.",
    "Demandez à l’API les noms de modèles et placez celui choisi dans la zone. Vous pouvez aussi en saisir un.",
    "Pida a la API los nombres de modelos y ponga el elegido en el cuadro. También puede escribir uno.",
    "Chiedi all’API i nomi dei modelli e metti quello scelto nella casella. Puoi anche digitarne uno.",
    "Peça à API os nomes dos modelos e coloque o escolhido na caixa. Também pode escrever um nome.",
    "Peça à API os nomes dos modelos e coloque o escolhido na caixa. Você também pode digitar um nome.",
    "Запросите у API имена моделей и вставьте выбранное в поле. Можно и ввести имя вручную.",
    "Запитайте в API назви моделей і вставте вибрану в поле. Можна й ввести назву вручну.",
    "Poproś API o nazwy modeli i wpisz wybraną w pole. Możesz też wpisać nazwę.",
    "Vraag de API om modelnamen en zet de gekozen in het vak. U kunt ook een naam typen.",
    "API’den model adlarını isteyin ve seçtiğinizi kutuya yazın. Bir ad da yazabilirsiniz.",
    "Hỏi API tên mô hình và đưa tên bạn chọn vào ô. Bạn cũng có thể tự nhập tên.")
add("Automatic send incomplete",
    "自动发送未完成", "自動傳送未完成", "自動送信が未完了", "자동 전송 미완료",
    "Automatisches Senden unvollständig", "Envoi automatique incomplet",
    "Envío automático incompleto", "Invio automatico incompleto",
    "Envio automático incompleto", "Envio automático incompleto",
    "Автоотправка не завершена", "Автонадсилання не завершено",
    "Automatyczne wysyłanie nieukończone", "Automatisch verzenden onvolledig",
    "Otomatik gönderim tamamlanmadı", "Gửi tự động chưa xong")
add("Back to toolbar",
    "返回工具栏", "返回工具列", "ツールバーに戻る", "도구 모음으로 돌아가기",
    "Zurück zur Symbolleiste", "Retour à la barre d’outils", "Volver a la barra de herramientas", "Torna alla barra degli strumenti",
    "Voltar à barra de ferramentas", "Voltar à barra de ferramentas", "Назад к панели инструментов", "Назад до панелі інструментів",
    "Wróć do paska narzędzi", "Terug naar werkbalk", "Araç çubuğuna dön", "Quay lại thanh công cụ")
add("Bake PDF",
    "固化 PDF", "固化 PDF", "PDF を焼き込み", "PDF 고정",
    "PDF einbrennen", "Figer le PDF", "Fijar PDF", "Blocca PDF",
    "Fixar PDF", "Fixar PDF", "Запечь PDF", "Запекти PDF",
    "Wypal PDF", "PDF vastzetten", "PDF’yi sabitle", "Cố định PDF")
add("Body structure sent to the web AI",
    "正文结构已发送到网页 AI", "正文結構已傳送到網頁 AI", "本文構造を Web AI に送信済み", "본문 구조를 웹 AI로 보냄",
    "Körperstruktur an Web-KI gesendet", "Structure du corps envoyée à l’IA web",
    "Estructura del cuerpo enviada a la IA web", "Struttura del corpo inviata all’IA web",
    "Estrutura do corpo enviada para a IA web", "Estrutura do corpo enviada à IA web",
    "Структура тела отправлена веб-ИИ", "Структуру тіла надіслано веб-ШІ",
    "Struktura treści wysłana do AI w sieci", "Tekststructuur naar web-AI verzonden",
    "Gövde yapısı web yapay zekâsına gönderildi", "Cấu trúc thân đã gửi tới AI web")
add("Bookmark extraction cancelled.",
    "书签提取已取消。", "書籤擷取已取消。", "しおりの抽出をキャンセルしました。", "책갈피 추출이 취소되었습니다.",
    "Lesezeichenextraktion abgebrochen.", "Extraction des signets annulée.",
    "Extracción de marcadores cancelada.", "Estrazione segnalibri annullata.",
    "Extração de marcadores cancelada.", "Extração de favoritos cancelada.",
    "Извлечение закладок отменено.", "Видобування закладок скасовано.",
    "Wyodrębnianie zakładek anulowane.", "Bladwijzerextractie geannuleerd.",
    "Yer imi çıkarma iptal edildi.", "Đã hủy trích xuất dấu trang.")
add("Bookmarks extracted.",
    "书签已提取。", "書籤已擷取。", "しおりを抽出しました。", "책갈피를 추출했습니다.",
    "Lesezeichen extrahiert.", "Signets extraits.", "Marcadores extraídos.", "Segnalibri estratti.",
    "Marcadores extraídos.", "Favoritos extraídos.", "Закладки извлечены.", "Закладки видобуто.",
    "Zakładki wyodrębnione.", "Bladwijzers geëxtraheerd.", "Yer imleri çıkarıldı.", "Đã trích xuất dấu trang.")
add("CJK Body Font",
    "CJK 正文字体", "CJK 正文字型", "CJK 本文フォント", "CJK 본문 글꼴",
    "CJK-Fließtextschrift", "Police du corps CJK", "Fuente del cuerpo CJK", "Carattere corpo CJK",
    "Tipo de letra do corpo CJK", "Fonte do corpo CJK", "Шрифт текста CJK", "Шрифт тексту CJK",
    "Czcionka tekstu CJK", "CJK-tekstlettertype", "CJK gövde yazı tipi", "Phông chữ thân CJK")
add("Calibrate TOC",
    "校准目录", "校準目錄", "目次を校正", "목차 보정",
    "Inhaltsverzeichnis kalibrieren", "Calibrer la table des matières",
    "Calibrar el índice", "Calibra l’indice",
    "Calibrar o índice", "Calibrar o sumário",
    "Калибровать оглавление", "Калібрувати зміст",
    "Kalibruj spis treści", "Inhoudsopgave kalibreren",
    "İçindekileri kalibre et", "Hiệu chỉnh mục lục")
add("Cancelled.",
    "已取消。", "已取消。", "キャンセルしました。", "취소되었습니다.",
    "Abgebrochen.", "Annulé.", "Cancelado.", "Annullato.",
    "Cancelado.", "Cancelado.", "Отменено.", "Скасовано.",
    "Anulowano.", "Geannuleerd.", "İptal edildi.", "Đã hủy.")
add("Cannot save '%s'",
    "无法保存“%s”", "無法儲存「%s」", "「%s」を保存できません", "'%s'을(를) 저장할 수 없습니다",
    "„%s“ kann nicht gespeichert werden", "Impossible d’enregistrer « %s »",
    "No se puede guardar «%s»", "Impossibile salvare «%s»",
    "Não é possível guardar «%s»", "Não é possível salvar \"%s\"",
    "Не удалось сохранить «%s»", "Не вдалося зберегти «%s»",
    "Nie można zapisać „%s”", "Kan ‘%s’ niet opslaan",
    "'%s' kaydedilemiyor", "Không thể lưu '%s'")
add("Cannot watch the clipboard. Close the window and try again. The prompt was not sent.",
    "无法监视剪贴板。请关闭窗口后重试。提示未发送。",
    "無法監視剪貼簿。請關閉視窗後重試。提示未傳送。",
    "クリップボードを監視できません。ウィンドウを閉じて再試行してください。プロンプトは送信されませんでした。",
    "클립보드를 감시할 수 없습니다. 창을 닫고 다시 시도하세요. 프롬프트가 전송되지 않았습니다.",
    "Zwischenablage kann nicht überwacht werden. Schließen Sie das Fenster und versuchen Sie es erneut. Die Eingabeaufforderung wurde nicht gesendet.",
    "Impossible de surveiller le Presse-papiers. Fermez la fenêtre et réessayez. L’invite n’a pas été envoyée.",
    "No se puede vigilar el portapapeles. Cierre la ventana e inténtelo de nuevo. No se envió el mensaje.",
    "Impossibile monitorare gli Appunti. Chiudi la finestra e riprova. Il prompt non è stato inviato.",
    "Não é possível vigiar a área de transferência. Feche a janela e tente novamente. O pedido não foi enviado.",
    "Não é possível vigiar a área de transferência. Feche a janela e tente novamente. O prompt não foi enviado.",
    "Не удалось следить за буфером обмена. Закройте окно и повторите попытку. Запрос не отправлен.",
    "Не вдалося стежити за буфером обміну. Закрийте вікно й спробуйте знову. Запит не надіслано.",
    "Nie można monitorować schowka. Zamknij okno i spróbuj ponownie. Monitu nie wysłano.",
    "Kan het klembord niet bewaken. Sluit het venster en probeer opnieuw. De prompt is niet verzonden.",
    "Pano izlenemiyor. Pencereyi kapatıp yeniden deneyin. İstem gönderilmedi.",
    "Không thể theo dõi clipboard. Đóng cửa sổ rồi thử lại. Lời nhắc chưa được gửi.")
add("Change Background Color",
    "更改背景颜色", "變更背景色彩", "背景色を変更", "배경색 변경",
    "Hintergrundfarbe ändern", "Changer la couleur d’arrière-plan", "Cambiar color de fondo", "Cambia colore di sfondo",
    "Alterar cor de fundo", "Alterar cor de fundo", "Изменить цвет фона", "Змінити колір тла",
    "Zmień kolor tła", "Achtergrondkleur wijzigen", "Arka plan rengini değiştir", "Đổi màu nền")
add("Change Scrollbar",
    "更改滚动条", "變更捲軸", "スクロールバーを変更", "스크롤바 변경",
    "Bildlaufleiste ändern", "Modifier la barre de défilement", "Cambiar barra de desplazamiento", "Cambia barra di scorrimento",
    "Alterar barra de deslocamento", "Alterar barra de rolagem", "Изменить полосу прокрутки", "Змінити смугу прокрутки",
    "Zmień pasek przewijania", "Schuifbalk wijzigen", "Kaydırma çubuğunu değiştir", "Đổi thanh cuộn")
add("Choose a model",
    "选择模型", "選擇模型", "モデルを選択", "모델 선택",
    "Modell wählen", "Choisir un modèle", "Elegir un modelo", "Scegli un modello",
    "Escolher um modelo", "Escolher um modelo", "Выберите модель", "Виберіть модель",
    "Wybierz model", "Kies een model", "Model seçin", "Chọn mô hình")
add("Choose the offline dictionary folder",
    "选择离线词典文件夹", "選擇離線詞典資料夾", "オフライン辞書フォルダーを選択", "오프라인 사전 폴더 선택",
    "Ordner für Offline-Wörterbuch wählen", "Choisir le dossier du dictionnaire hors ligne",
    "Elegir la carpeta del diccionario sin conexión", "Scegli la cartella del dizionario offline",
    "Escolher a pasta do dicionário offline", "Escolher a pasta do dicionário offline",
    "Выберите папку автономного словаря", "Виберіть теку автономного словника",
    "Wybierz folder słownika offline", "Map voor offlinewoordenboek kiezen",
    "Çevrimdışı sözlük klasörünü seçin", "Chọn thư mục từ điển ngoại tuyến")
add("Clear search text",
    "清除搜索文本", "清除搜尋文字", "検索テキストをクリア", "검색어 지우기",
    "Suchtext löschen", "Effacer le texte de recherche", "Borrar texto de búsqueda", "Cancella testo di ricerca",
    "Limpar texto de pesquisa", "Limpar texto de pesquisa", "Очистить текст поиска", "Очистити текст пошуку",
    "Wyczyść tekst wyszukiwania", "Zoektekst wissen", "Arama metnini temizle", "Xóa chữ tìm kiếm")
add("Clipboard is temporarily unreadable. Retrying; you can also copy the AI reply again.",
    "剪贴板暂时无法读取。正在重试；您也可以再次复制 AI 回复。",
    "剪貼簿暫時無法讀取。正在重試；您也可以再次複製 AI 回覆。",
    "クリップボードを一時的に読み取れません。再試行中です。AI の返信を再度コピーすることもできます。",
    "클립보드를 잠시 읽을 수 없습니다. 다시 시도 중이며, AI 응답을 다시 복사할 수도 있습니다.",
    "Zwischenablage vorübergehend nicht lesbar. Erneuter Versuch; Sie können die KI-Antwort auch erneut kopieren.",
    "Presse-papiers temporairement illisible. Nouvelle tentative ; vous pouvez aussi recopier la réponse de l’IA.",
    "El portapapeles no se puede leer temporalmente. Reintentando; también puede copiar de nuevo la respuesta de la IA.",
    "Appunti temporaneamente illeggibili. Nuovo tentativo; puoi anche ricopiare la risposta dell’IA.",
    "Área de transferência temporariamente ilegível. A tentar novamente; também pode copiar de novo a resposta da IA.",
    "Área de transferência temporariamente ilegível. Tentando novamente; você também pode copiar de novo a resposta da IA.",
    "Буфер обмена временно недоступен. Повтор; можно снова скопировать ответ ИИ.",
    "Буфер обміну тимчасово недоступний. Повтор; можна знову скопіювати відповідь ШІ.",
    "Schowek tymczasowo nieczytelny. Ponawianie; możesz też ponownie skopiować odpowiedź AI.",
    "Klembord tijdelijk onleesbaar. Opnieuw proberen; u kunt het AI-antwoord ook opnieuw kopiëren.",
    "Pano geçici olarak okunamıyor. Yeniden deneniyor; AI yanıtını yeniden de kopyalayabilirsiniz.",
    "Clipboard tạm thời không đọc được. Đang thử lại; bạn cũng có thể sao chép lại phản hồi AI.")
add("Collecting list of printers",
    "正在收集打印机列表", "正在收集印表機清單", "プリンター一覧を収集中", "프린터 목록 수집 중",
    "Druckerliste wird erfasst", "Collecte de la liste des imprimantes",
    "Recopilando la lista de impresoras", "Raccolta elenco stampanti",
    "A recolher a lista de impressoras", "Coletando a lista de impressoras",
    "Сбор списка принтеров", "Збір списку принтерів",
    "Zbieranie listy drukarek", "Printerlijst verzamelen",
    "Yazıcı listesi toplanıyor", "Đang thu thập danh sách máy in")
add("Command invoked when you double-click a PDF document:",
    "双击 PDF 文档时调用的命令：", "連按兩下 PDF 文件時叫用的命令：", "PDF をダブルクリックしたときに実行するコマンド:",
    "PDF 문서를 두 번 클릭할 때 실행되는 명령:",
    "Befehl beim Doppelklicken auf ein PDF-Dokument:",
    "Commande invoquée lors d’un double-clic sur un document PDF :",
    "Comando al hacer doble clic en un documento PDF:",
    "Comando richiamato con doppio clic su un documento PDF:",
    "Comando invocado ao fazer duplo clique num documento PDF:",
    "Comando invocado ao clicar duas vezes em um documento PDF:",
    "Команда при двойном щелчке по PDF-документу:",
    "Команда при подвійному клацанні по PDF-документу:",
    "Polecenie przy dwukrotnym kliknięciu dokumentu PDF:",
    "Opdracht bij dubbelklikken op een PDF-document:",
    "PDF belgesine çift tıklanınca çalıştırılan komut:",
    "Lệnh khi nhấp đúp tài liệu PDF:")
add("Compress PDF",
    "压缩 PDF", "壓縮 PDF", "PDF を圧縮", "PDF 압축",
    "PDF komprimieren", "Compresser le PDF", "Comprimir PDF", "Comprimi PDF",
    "Comprimir PDF", "Comprimir PDF", "Сжать PDF", "Стиснути PDF",
    "Kompresuj PDF", "PDF comprimeren", "PDF’yi sıkıştır", "Nén PDF")
add("Contacting the API...",
    "正在连接 API…", "正在連線 API…", "API に接続中...", "API에 연결 중...",
    "API wird kontaktiert…", "Contact de l’API…", "Contactando la API…", "Contatto dell’API…",
    "A contactar a API…", "Contatando a API…", "Обращение к API…", "Звернення до API…",
    "Kontaktowanie API…", "API wordt benaderd…", "API ile iletişim kuruluyor…", "Đang kết nối API…")
add("Contents page",
    "目录页", "目錄頁", "目次ページ", "목차 페이지",
    "Inhaltsseite", "Page de sommaire", "Página de contenido", "Pagina dei contenuti",
    "Página de conteúdos", "Página de sumário", "Страница оглавления", "Сторінка змісту",
    "Strona spisu treści", "Inhoudspagina", "İçindekiler sayfası", "Trang mục lục")
add("Copied",
    "已复制", "已複製", "コピーしました", "복사됨",
    "Kopiert", "Copié", "Copiado", "Copiato",
    "Copiado", "Copiado", "Скопировано", "Скопійовано",
    "Skopiowano", "Gekopieerd", "Kopyalandı", "Đã sao chép")
add("Copied.",
    "已复制。", "已複製。", "コピーしました。", "복사했습니다.",
    "Kopiert.", "Copié.", "Copiado.", "Copiato.",
    "Copiado.", "Copiado.", "Скопировано.", "Скопійовано.",
    "Skopiowano.", "Gekopieerd.", "Kopyalandı.", "Đã sao chép.")
add("Copy translation",
    "复制译文", "複製譯文", "翻訳をコピー", "번역 복사",
    "Übersetzung kopieren", "Copier la traduction", "Copiar traducción", "Copia traduzione",
    "Copiar tradução", "Copiar tradução", "Копировать перевод", "Копіювати переклад",
    "Kopiuj tłumaczenie", "Vertaling kopiëren", "Çeviriyi kopyala", "Sao chép bản dịch")
add("Copying text was denied",
    "复制文本被拒绝", "複製文字被拒", "テキストのコピーが拒否されました", "텍스트 복사가 거부됨",
    "Textkopieren wurde verweigert", "La copie du texte a été refusée",
    "Se denegó la copia de texto", "Copia del testo negata",
    "A cópia de texto foi recusada", "A cópia de texto foi negada",
    "Копирование текста отклонено", "Копіювання тексту відхилено",
    "Kopiowanie tekstu odrzucone", "Tekst kopiëren geweigerd",
    "Metin kopyalama reddedildi", "Sao chép văn bản bị từ chối")
add("Could not find this heading in the body",
    "在正文中找不到此标题", "在正文中找不到此標題", "本文でこの見出しが見つかりません", "본문에서 이 제목을 찾을 수 없음",
    "Diese Überschrift wurde im Textkörper nicht gefunden", "Impossible de trouver ce titre dans le corps",
    "No se encontró este encabezado en el cuerpo", "Impossibile trovare questa intestazione nel corpo",
    "Não foi possível encontrar este título no corpo", "Não foi possível encontrar este título no corpo",
    "Не удалось найти этот заголовок в тексте", "Не вдалося знайти цей заголовок у тексті",
    "Nie znaleziono tego nagłówka w treści", "Deze kop is niet in de tekst gevonden",
    "Bu başlık gövdede bulunamadı", "Không tìm thấy tiêu đề này trong thân bài")
add("Could not recognize text on this page.",
    "无法识别此页上的文本。", "無法辨識此頁上的文字。", "このページのテキストを認識できませんでした。", "이 페이지의 텍스트를 인식하지 못했습니다.",
    "Text auf dieser Seite konnte nicht erkannt werden.", "Impossible de reconnaître le texte de cette page.",
    "No se pudo reconocer el texto de esta página.", "Impossibile riconoscere il testo di questa pagina.",
    "Não foi possível reconhecer o texto desta página.", "Não foi possível reconhecer o texto desta página.",
    "Не удалось распознать текст на этой странице.", "Не вдалося розпізнати текст на цій сторінці.",
    "Nie rozpoznano tekstu na tej stronie.", "Tekst op deze pagina kon niet worden herkend.",
    "Bu sayfadaki metin tanınamadı.", "Không nhận dạng được chữ trên trang này.")
add("Could not save searchable PDF.",
    "无法保存可搜索 PDF。", "無法儲存可搜尋 PDF。", "検索可能な PDF を保存できませんでした。", "검색 가능한 PDF를 저장하지 못했습니다.",
    "Durchsuchbares PDF konnte nicht gespeichert werden.", "Impossible d’enregistrer le PDF consultable.",
    "No se pudo guardar el PDF con búsqueda.", "Impossibile salvare il PDF ricercabile.",
    "Não foi possível guardar o PDF pesquisável.", "Não foi possível salvar o PDF pesquisável.",
    "Не удалось сохранить PDF с поиском.", "Не вдалося зберегти PDF з пошуком.",
    "Nie udało się zapisać przeszukiwalnego PDF.", "Doorzoekbare PDF kon niet worden opgeslagen.",
    "Aranabilir PDF kaydedilemedi.", "Không lưu được PDF có thể tìm kiếm.")
add("Couldn't add the signature.",
    "无法添加签名。", "無法新增簽章。", "署名を追加できませんでした。", "서명을 추가하지 못했습니다.",
    "Signatur konnte nicht hinzugefügt werden.", "Impossible d’ajouter la signature.",
    "No se pudo añadir la firma.", "Impossibile aggiungere la firma.",
    "Não foi possível adicionar a assinatura.", "Não foi possível adicionar a assinatura.",
    "Не удалось добавить подпись.", "Не вдалося додати підпис.",
    "Nie udało się dodać podpisu.", "Handtekening kon niet worden toegevoegd.",
    "İmza eklenemedi.", "Không thêm được chữ ký.")
add("Couldn't read that image.",
    "无法读取该图像。", "無法讀取該影像。", "その画像を読み取れませんでした。", "해당 이미지를 읽지 못했습니다.",
    "Dieses Bild konnte nicht gelesen werden.", "Impossible de lire cette image.",
    "No se pudo leer esa imagen.", "Impossibile leggere quell’immagine.",
    "Não foi possível ler essa imagem.", "Não foi possível ler essa imagem.",
    "Не удалось прочитать это изображение.", "Не вдалося прочитати це зображення.",
    "Nie udało się odczytać tego obrazu.", "Die afbeelding kon niet worden gelezen.",
    "Bu görüntü okunamadı.", "Không đọc được ảnh đó.")
add("Crop Image",
    "裁剪图像", "裁切影像", "画像を切り抜き", "이미지 자르기",
    "Bild zuschneiden", "Recadrer l’image", "Recortar imagen", "Ritaglia immagine",
    "Recortar imagem", "Recortar imagem", "Обрезать изображение", "Обрізати зображення",
    "Przytnij obraz", "Afbeelding bijsnijden", "Görüntüyü kırp", "Cắt ảnh")
add("Ctrl+Tab to navigate",
    "Ctrl+Tab 导航", "Ctrl+Tab 巡覽", "Ctrl+Tab で移動", "Ctrl+Tab으로 이동",
    "Strg+Tab zum Navigieren", "Ctrl+Tab pour naviguer", "Ctrl+Tab para navegar", "Ctrl+Tab per navigare",
    "Ctrl+Tab para navegar", "Ctrl+Tab para navegar", "Ctrl+Tab для навигации", "Ctrl+Tab для навігації",
    "Ctrl+Tab do nawigacji", "Ctrl+Tab om te navigeren", "Gezinmek için Ctrl+Tab", "Ctrl+Tab để điều hướng")
add("Custom DPI must be 0 (automatic) or between 72 and 600.",
    "自定义 DPI 必须为 0（自动）或介于 72 与 600 之间。",
    "自訂 DPI 必須為 0（自動）或介於 72 與 600 之間。",
    "カスタム DPI は 0（自動）または 72～600 である必要があります。",
    "사용자 지정 DPI는 0(자동)이거나 72에서 600 사이여야 합니다.",
    "Benutzerdefiniertes DPI muss 0 (automatisch) oder zwischen 72 und 600 liegen.",
    "Le DPI personnalisé doit être 0 (automatique) ou compris entre 72 et 600.",
    "El DPI personalizado debe ser 0 (automático) o estar entre 72 y 600.",
    "Il DPI personalizzato deve essere 0 (automatico) o compreso tra 72 e 600.",
    "O DPI personalizado deve ser 0 (automático) ou entre 72 e 600.",
    "O DPI personalizado deve ser 0 (automático) ou entre 72 e 600.",
    "Пользовательский DPI должен быть 0 (авто) или от 72 до 600.",
    "Користувацький DPI має бути 0 (авто) або від 72 до 600.",
    "Niestandardowe DPI musi być 0 (automatycznie) lub między 72 a 600.",
    "Aangepaste DPI moet 0 (automatisch) of tussen 72 en 600 zijn.",
    "Özel DPI 0 (otomatik) veya 72 ile 600 arasında olmalıdır.",
    "DPI tùy chỉnh phải là 0 (tự động) hoặc từ 72 đến 600.")
add("Decompress PDF",
    "解压 PDF", "解壓縮 PDF", "PDF を展開", "PDF 압축 해제",
    "PDF dekomprimieren", "Décompresser le PDF", "Descomprimir PDF", "Decomprimi PDF",
    "Descomprimir PDF", "Descomprimir PDF", "Распаковать PDF", "Розпакувати PDF",
    "Dekompresuj PDF", "PDF decomprimeren", "PDF sıkıştırmasını aç", "Giải nén PDF")
add("Decrypt PDF",
    "解密 PDF", "解密 PDF", "PDF を復号", "PDF 암호 해제",
    "PDF entschlüsseln", "Déchiffrer le PDF", "Descifrar PDF", "Decripta PDF",
    "Desencriptar PDF", "Descriptografar PDF", "Расшифровать PDF", "Розшифрувати PDF",
    "Odszyfruj PDF", "PDF ontsleutelen", "PDF’nin şifresini çöz", "Giải mã PDF")
add("Delete %d TOC items and their child items?",
    "删除 %d 个目录项及其子项？", "刪除 %d 個目錄項目及其子項目？", "%d 件の目次項目とその子項目を削除しますか？",
    "목차 항목 %d개와 하위 항목을 삭제할까요?",
    "%d Inhaltsverzeichniseinträge und ihre Unterelemente löschen?",
    "Supprimer %d entrées de table des matières et leurs enfants ?",
    "¿Eliminar %d entradas de índice y sus elementos secundarios?",
    "Eliminare %d voci dell’indice e le relative voci figlie?",
    "Eliminar %d entradas de índice e os respetivos itens subordinados?",
    "Excluir %d itens de sumário e seus itens filhos?",
    "Удалить %d пунктов оглавления вместе с дочерними?",
    "Видалити %d пунктів змісту разом із дочірніми?",
    "Usunąć %d pozycji spisu treści wraz z podrzędnymi?",
    "%d inhoudsopgave-items en hun onderliggende items verwijderen?",
    "%d içindekiler öğesini ve alt öğelerini silinsin mi?",
    "Xóa %d mục lục và các mục con?")
add("Delete %d TOC items?",
    "删除 %d 个目录项？", "刪除 %d 個目錄項目？", "%d 件の目次項目を削除しますか？", "목차 항목 %d개를 삭제할까요?",
    "%d Inhaltsverzeichniseinträge löschen?", "Supprimer %d entrées de table des matières ?",
    "¿Eliminar %d entradas de índice?", "Eliminare %d voci dell’indice?",
    "Eliminar %d entradas de índice?", "Excluir %d itens de sumário?",
    "Удалить %d пунктов оглавления?", "Видалити %d пунктів змісту?",
    "Usunąć %d pozycji spisu treści?", "%d inhoudsopgave-items verwijderen?",
    "%d içindekiler öğesi silinsin mi?", "Xóa %d mục lục?")
add("Delete %d TOC items? Child items will be moved up one level.",
    "删除 %d 个目录项？子项将上移一级。", "刪除 %d 個目錄項目？子項目將上移一層。",
    "%d 件の目次項目を削除しますか？子項目は 1 つ上の階層に移動します。",
    "목차 항목 %d개를 삭제할까요? 하위 항목은 한 단계 위로 올라갑니다.",
    "%d Inhaltsverzeichniseinträge löschen? Unterelemente werden eine Ebene nach oben verschoben.",
    "Supprimer %d entrées de table des matières ? Les enfants monteront d’un niveau.",
    "¿Eliminar %d entradas de índice? Los elementos secundarios subirán un nivel.",
    "Eliminare %d voci dell’indice? Le voci figlie saliranno di un livello.",
    "Eliminar %d entradas de índice? Os itens subordinados sobem um nível.",
    "Excluir %d itens de sumário? Os itens filhos sobem um nível.",
    "Удалить %d пунктов оглавления? Дочерние поднимутся на уровень выше.",
    "Видалити %d пунктів змісту? Дочірні піднімуться на рівень вище.",
    "Usunąć %d pozycji spisu treści? Elementy podrzędne awansują o poziom.",
    "%d inhoudsopgave-items verwijderen? Onderliggende items gaan een niveau omhoog.",
    "%d içindekiler öğesi silinsin mi? Alt öğeler bir düzey yukarı taşınır.",
    "Xóa %d mục lục? Các mục con sẽ lên một cấp.")
add("Delete File",
    "删除文件", "刪除檔案", "ファイルを削除", "파일 삭제",
    "Datei löschen", "Supprimer le fichier", "Eliminar archivo", "Elimina file",
    "Eliminar ficheiro", "Excluir arquivo", "Удалить файл", "Видалити файл",
    "Usuń plik", "Bestand verwijderen", "Dosyayı sil", "Xóa tệp")
add("Delete Pages",
    "删除页面", "刪除頁面", "ページを削除", "페이지 삭제",
    "Seiten löschen", "Supprimer des pages", "Eliminar páginas", "Elimina pagine",
    "Eliminar páginas", "Excluir páginas", "Удалить страницы", "Видалити сторінки",
    "Usuń strony", "Pagina’s verwijderen", "Sayfaları sil", "Xóa trang")
add("Delete Pages From PDF",
    "从 PDF 删除页面", "從 PDF 刪除頁面", "PDF からページを削除", "PDF에서 페이지 삭제",
    "Seiten aus PDF löschen", "Supprimer des pages du PDF", "Eliminar páginas del PDF", "Elimina pagine dal PDF",
    "Eliminar páginas do PDF", "Excluir páginas do PDF", "Удалить страницы из PDF", "Видалити сторінки з PDF",
    "Usuń strony z PDF", "Pagina’s uit PDF verwijderen", "PDF’den sayfa sil", "Xóa trang khỏi PDF")
add("Delete these %d files? They will be moved to the Recycle Bin.",
    "删除这 %d 个文件？它们将移至回收站。", "刪除這 %d 個檔案？它們將移至資源回收筒。",
    "これら %d 個のファイルを削除しますか？ごみ箱に移動します。",
    "이 파일 %d개를 삭제할까요? 휴지통으로 이동합니다.",
    "Diese %d Dateien löschen? Sie werden in den Papierkorb verschoben.",
    "Supprimer ces %d fichiers ? Ils seront déplacés vers la Corbeille.",
    "¿Eliminar estos %d archivos? Se moverán a la Papelera de reciclaje.",
    "Eliminare questi %d file? Verranno spostati nel Cestino.",
    "Eliminar estes %d ficheiros? Serão movidos para a Reciclagem.",
    "Excluir estes %d arquivos? Eles serão movidos para a Lixeira.",
    "Удалить эти %d файлов? Они будут перемещены в Корзину.",
    "Видалити ці %d файлів? Їх буде переміщено до Кошика.",
    "Usunąć te %d plików? Trafią do Kosza.",
    "Deze %d bestanden verwijderen? Ze gaan naar de Prullenbak.",
    "Bu %d dosya silinsin mi? Geri Dönüşüm Kutusu’na taşınırlar.",
    "Xóa %d tệp này? Chúng sẽ được chuyển vào Thùng rác.")
add("Delete this TOC item and all of its child items?",
    "删除此目录项及其所有子项？", "刪除此目錄項目及其所有子項目？",
    "この目次項目とすべての子項目を削除しますか？", "이 목차 항목과 모든 하위 항목을 삭제할까요?",
    "Diesen Inhaltsverzeichniseintrag und alle Unterelemente löschen?",
    "Supprimer cette entrée de table des matières et tous ses enfants ?",
    "¿Eliminar esta entrada de índice y todos sus elementos secundarios?",
    "Eliminare questa voce dell’indice e tutte le voci figlie?",
    "Eliminar esta entrada de índice e todos os itens subordinados?",
    "Excluir este item de sumário e todos os itens filhos?",
    "Удалить этот пункт оглавления и все дочерние?",
    "Видалити цей пункт змісту та всі дочірні?",
    "Usunąć tę pozycję spisu treści wraz ze wszystkimi podrzędnymi?",
    "Dit inhoudsopgave-item en alle onderliggende items verwijderen?",
    "Bu içindekiler öğesi ve tüm alt öğeleri silinsin mi?",
    "Xóa mục lục này và mọi mục con?")
add("Delete this TOC item?",
    "删除此目录项？", "刪除此目錄項目？", "この目次項目を削除しますか？", "이 목차 항목을 삭제할까요?",
    "Diesen Inhaltsverzeichniseintrag löschen?", "Supprimer cette entrée de table des matières ?",
    "¿Eliminar esta entrada de índice?", "Eliminare questa voce dell’indice?",
    "Eliminar esta entrada de índice?", "Excluir este item de sumário?",
    "Удалить этот пункт оглавления?", "Видалити цей пункт змісту?",
    "Usunąć tę pozycję spisu treści?", "Dit inhoudsopgave-item verwijderen?",
    "Bu içindekiler öğesi silinsin mi?", "Xóa mục lục này?")
add("Delete this TOC item? Child items will be moved up one level.",
    "删除此目录项？子项将上移一级。", "刪除此目錄項目？子項目將上移一層。",
    "この目次項目を削除しますか？子項目は 1 つ上の階層に移動します。",
    "이 목차 항목을 삭제할까요? 하위 항목은 한 단계 위로 올라갑니다.",
    "Diesen Inhaltsverzeichniseintrag löschen? Unterelemente werden eine Ebene nach oben verschoben.",
    "Supprimer cette entrée ? Les enfants monteront d’un niveau.",
    "¿Eliminar esta entrada? Los elementos secundarios subirán un nivel.",
    "Eliminare questa voce? Le voci figlie saliranno di un livello.",
    "Eliminar esta entrada? Os itens subordinados sobem um nível.",
    "Excluir este item? Os itens filhos sobem um nível.",
    "Удалить этот пункт? Дочерние поднимутся на уровень выше.",
    "Видалити цей пункт? Дочірні піднімуться на рівень вище.",
    "Usunąć tę pozycję? Elementy podrzędne awansują o poziom.",
    "Dit item verwijderen? Onderliggende items gaan een niveau omhoog.",
    "Bu öğe silinsin mi? Alt öğeler bir düzey yukarı taşınır.",
    "Xóa mục này? Các mục con sẽ lên một cấp.")
add("Delete this file? It will be moved to the Recycle Bin.",
    "删除此文件？它将移至回收站。", "刪除此檔案？它將移至資源回收筒。",
    "このファイルを削除しますか？ごみ箱に移動します。", "이 파일을 삭제할까요? 휴지통으로 이동합니다.",
    "Diese Datei löschen? Sie wird in den Papierkorb verschoben.",
    "Supprimer ce fichier ? Il sera déplacé vers la Corbeille.",
    "¿Eliminar este archivo? Se moverá a la Papelera de reciclaje.",
    "Eliminare questo file? Verrà spostato nel Cestino.",
    "Eliminar este ficheiro? Será movido para a Reciclagem.",
    "Excluir este arquivo? Ele será movido para a Lixeira.",
    "Удалить этот файл? Он будет перемещён в Корзину.",
    "Видалити цей файл? Його буде переміщено до Кошика.",
    "Usunąć ten plik? Trafi do Kosza.",
    "Dit bestand verwijderen? Het gaat naar de Prullenbak.",
    "Bu dosya silinsin mi? Geri Dönüşüm Kutusu’na taşınır.",
    "Xóa tệp này? Nó sẽ được chuyển vào Thùng rác.")
add("Deskew cleared.",
    "已清除纠偏。", "已清除糾偏。", "傾き補正をクリアしました。", "기울기 보정을 지웠습니다.",
    "Schräglagenkorrektur gelöscht.", "Redressement effacé.", "Corrección de inclinación borrada.", "Raddrizzamento cancellato.",
    "Correção de inclinação limpa.", "Correção de inclinação limpa.", "Выравнивание сброшено.", "Вирівнювання скинуто.",
    "Wyrównanie wyczyszczone.", "Scheefstandcorrectie gewist.", "Eğrilik düzeltmesi temizlendi.", "Đã xóa chỉnh nghiêng.")
add("Detailed Search",
    "详细搜索", "詳細搜尋", "詳細検索", "상세 검색",
    "Detaillierte Suche", "Recherche détaillée", "Búsqueda detallada", "Ricerca dettagliata",
    "Pesquisa detalhada", "Pesquisa detalhada", "Подробный поиск", "Детальний пошук",
    "Szczegółowe wyszukiwanie", "Gedetailleerd zoeken", "Ayrıntılı arama", "Tìm kiếm chi tiết")
# fmt: on


def main() -> None:
    out: dict[str, dict[str, str]] = {}
    for key, vals in T.items():
        out[key] = dict(zip(LANGS, vals))
    path = ROOT / "cmd" / "_fills_part_hand_a.json"
    path.write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {path.name} keys={len(out)}")


if __name__ == "__main__":
    main()
