/* Copyright 2022 the SumatraPDF project authors (see AUTHORS file).
   License: Simplified BSD (see COPYING.BSD) */

// must match order in gAllIcons
enum class TbIcon {
    Text = -2,
    None = -1,
    Open = 0,
    Print,
    PagePrev,
    PageNext,
    LayoutContinuous,
    LayoutSinglePage,
    ZoomOut,
    ZoomIn,
    SearchPrev,
    SearchNext,
    MatchCase,
    MatchCase2,
    Save,
    Bookmark,
    RotateLeft,
    RotateRight,
    DocColorOriginal,
    ThemeMoon,
    DocColorAuto,
    DocColorFollowTheme,
    Dictionary,
    Speak,
    PauseSpeaking,
    NavigateBack,
    NavigateForward,
    Search,
    ChevronUp,
    ChevronDown,
    HomeList,
    HomeThumbnails,
    Close,
    Pin,
    ArrowsDiagonal,
    ArrowsDiagonalMinimize,
    MatchWholeWord,
    EbookFontSizeDecrease,
    EbookFontSizeIncrease,
    AnnotText,
    AnnotSquare,
    AnnotCircle,
    AnnotLine,
    AnnotInk,
    Ocr,
    MapPin,
    MergeUp,
    Link,
    CalibrateToc,
    AnnotStamp,
    Fullscreen,
    FullscreenExit,
    kMax
};

const char* GetSvgIcon(TbIcon);
