/* Copyright 2026 the SumatraPDF project authors (see AUTHORS file).
   License: GPLv3 */

#include "utils/BaseUtil.h"
#include "TocAiPrompts.h"

// First-round body-TOC prompt. The AI receives ONLY compressed heading
// candidates (id / PDF page / original text), never the body text or page
// images. It may select candidates and assign levels; it may not invent
// headings, rewrite titles or guess pages.
static const char* kBodyTocPromptPreamble =
    "你正在帮助一个 PDF 阅读器恢复文档的电子目录（TOC）。\n"
    "\n"
    "下面的数据不是完整正文，而是软件对【整份 PDF】进行本地快速扫描后得到的“疑似标题候选”。\n"
    "每个候选都有唯一 candidate_id。\n"
    "\n"
    "软件本地已经保存：\n"
    "- 原始标题文字\n"
    "- PDF 页码\n"
    "- 页面位置\n"
    "- 跳转目标\n"
    "\n"
    "因此：\n"
    "你不需要猜页码；\n"
    "你不需要生成跳转位置；\n"
    "你不需要重新改写标题。\n"
    "\n"
    "你的任务只有：\n"
    "1. 判断哪些候选是真正的章节 / 小节标题；\n"
    "2. 删除正文短句、页眉页脚、表格内容、图题、表题等噪声；\n"
    "3. 判断真正标题之间的层级；\n"
    "4. 检查文档结构是否可能存在遗漏。\n"
    "\n"
    "请结合：\n"
    "- 标题编号\n"
    "- 编号连续性\n"
    "- 页面顺序\n"
    "- 标题措辞\n"
    "- 全局层级关系\n"
    "进行判断。\n"
    "\n"
    "常见中文结构包括但不限于：\n"
    "第一章 / 第二章\n"
    "第一节 / 第二节\n"
    "一、\n"
    "二、\n"
    "（一）\n"
    "（二）\n"
    "1.\n"
    "1.1\n"
    "1.1.1\n"
    "1、\n"
    "（1）\n"
    "前言\n"
    "引言\n"
    "结论\n"
    "附录\n"
    "附件\n"
    "参考文献\n"
    "\n"
    "但是：\n"
    "编号符合格式不代表一定是标题。\n"
    "没有编号的独立短标题也可能是真标题。\n"
    "\n"
    "<rules>\n"
    "\n"
    "1. 正式 TOC 只能从提供的 candidate 中选择。\n"
    "2. 不得编造 candidate_id。\n"
    "3. 不得编造不存在的标题。\n"
    "4. 不得自己填写或修改 PDF 页码。\n"
    "5. 不得润色、重写或简化标题。\n"
    "6. 如果怀疑存在缺失标题，但候选中没有：不要猜标题，只在 suspected_gaps 中返回需要软件重新检查的 PDF 页码范围。\n"
    "7. level 使用整数：1 = 一级，2 = 二级，3 = 三级，4 = 四级。\n"
    "8. 同一编号体系的层级应尽量保持一致。例如：第一章 → 一、 → （一）；或者 1 → 1.1 → 1.1.1。\n"
    "9. 公文层级规则：一、二、三、为一级；其下是（一）（二）为二级；再下是 1. 2. 为三级；"
    "同一父标题下不应混用（一）与 1. 作为同一级。\n"
    "\n"
    "</rules>\n"
    "\n"
    "<gap_check>\n"
    "\n"
    "完成目录以后检查：\n"
    "\n"
    "A. 编号是否断裂。\n"
    "例如第一章、第二章、第四章可能缺第三章；3.1、3.2、3.4 可能缺 3.3；（一）（二）（四）可能缺（三）。\n"
    "\n"
    "B. 是否存在异常长的无标题 PDF 页区间。\n"
    "如果认为某一范围很可疑，加入 suspected_gaps。suspected_gaps 只是让软件重新检查，不得自行创建缺失标题。\n"
    "\n"
    "</gap_check>\n"
    "\n"
    "<output_format>\n"
    "\n"
    "严格只输出一个 JSON 对象。\n"
    "不要输出 Markdown、代码围栏、解释、前言、总结或注释。\n"
    "\n"
    "格式：\n"
    "{\n"
    "  \"toc\": [\n"
    "    { \"candidate_id\": \"C00012\", \"level\": 1 },\n"
    "    { \"candidate_id\": \"C00018\", \"level\": 2 }\n"
    "  ],\n"
    "  \"suspected_gaps\": [\n"
    "    { \"start_pdf_page\": 63, \"end_pdf_page\": 78, \"reason\": \"章节编号从第二章直接进入第四章，可能存在遗漏\" }\n"
    "  ]\n"
    "}\n"
    "如果没有可疑遗漏：\"suspected_gaps\": []。\n"
    "\n"
    "</output_format>\n";

static const char* kBodyTocPromptEpilogue =
    "\n</candidates>\n"
    "\n"
    "请恢复文档真实的 TOC。\n"
    "再次强调：只能引用已有 candidate_id；不要编造标题；不要编造页码；只输出 JSON。\n";

char* BuildBodyTocPrompt(int totalPages, const char* candidateDigest) {
    StrBuilder out;
    out.Append(kBodyTocPromptPreamble);
    out.AppendFmt("<document>\n\nPDF_TOTAL_PAGES=%d\n\n</document>\n\n<candidates>\n", totalPages);
    if (candidateDigest) {
        out.Append(candidateDigest);
    }
    out.Append(kBodyTocPromptEpilogue);
    return out.StealData();
}
